# Font configuration
font:
  # Point size
  size: 7.0
  #normal:
  # Font family
  #
  # Default:
  #   - (macOS) Menlo
  #   - (Linux/BSD) monospace
  #   - (Windows) Consolas
  #family: monospace

  # The `style` can be specified to pick a specific face.
  #style: Regular

  # Bold font face
  #bold:
  # Font family
  #
  # If the bold family is not specified, it will fall back to the
  # value specified for the normal font.
  #family: monospace

  # The `style` can be specified to pick a specific face.
  #style: Bold

  # Italic font face
  #italic:
  # Font family
  #
  # If the italic family is not specified, it will fall back to the
  # value specified for the normal font.
  #family: monospace

  # The `style` can be specified to pick a specific face.
  #style: Italic

  # Bold italic font face
  #bold_italic:
  # Font family
  #
  # If the bold italic family is not specified, it will fall back to the
  # value specified for the normal font.
  #family: monospace

  # The `style` can be specified to pick a specific face.
  #style: Bold Italic


colors:
  primary:
    background: '0x23252e'
    foreground: '0xFFFFFF'

  normal:
    black:   '0x1F2229'
    red:     '0xD41919'
    green:   '0x5EBDAB'
    yellow:  '0xFEA44C'
    blue:    '0x367BF0'
    magenta: '0x9755B3'
    cyan:    '0x49AEE6'
    white:   '0xE6E6E6'

  bright:
    black:   '0x198388'
    red:     '0xEC0101'
    green:   '0x47D4B9'
    yellow:  '0xFF8A18'
    blue:    '0x277FFF'
    magenta: '0x962AC3'
    cyan:    '0x05A1F7'
    white:   '0xFFFFFF'
